Allow multiple response examples to be defined per status code and content type
For example:

  response 422, 'invalid request' do
    example 'name is missing'
      let(:password) { 'secret' }
      run_test!
    end

    example 'password is missing' do
      let(:name) { 'bobby' }
      run_test!
    end

    example 'bad content type' do
      examples 'text/plain' => {
        error: 'bad content type'
      }
    end
  end